; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=hs32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=HS32

define i32 @addi(i32 %a) nounwind {
; HS32-LABEL: addi:
; HS32:       ; %bb.0:
; HS32-NEXT:    add r10, r1, 10
; HS32-NEXT:    mov pc, lr
  %1 = add i32 %a, 10
  ret i32 %1
}
