; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=hs32 -verify-machineinstrs < %s \
; RUN:   | FileCheck %s -check-prefix=HS32

define i32 @mov_small_pos() nounwind {
; HS32-LABEL: mov_small_pos:
; HS32:       ; %bb.0:
; HS32-NEXT:    mov r10, 12
; HS32-NEXT:    mov pc, lr
    ret i32 12
}

define i32 @mov_small_neg() nounwind {
; HS32-LABEL: mov_small_neg:
; HS32:       ; %bb.0:
; HS32-NEXT:    mov r10, -2
; HS32-NEXT:    mov pc, lr
    ret i32 -2
}

define i32 @mov_large_pos() nounwind {
; HS32-LABEL: mov_large_pos:
; HS32:       ; %bb.0:
; HS32-NEXT:    mov r10, 24910
; HS32-NEXT:    movt r10, 188
; HS32-NEXT:    mov pc, lr
    ret i32 12345678
}

define i32 @mov_large_neg() nounwind {
; HS32-LABEL: mov_large_neg:
; HS32:       ; %bb.0:
; HS32-NEXT:    mov r10, 40626
; HS32-NEXT:    movt r10, 65347
; HS32-NEXT:    mov pc, lr
    ret i32 -12345678
}
